### ISSUE TITLE
Testing framework (Jest)

### ISSUE THREAD

**Issue by maktarsis** [maktarsis/routeshub#199]
**Is your feature request related to a problem? Please describe.**
Angular 8 has **builders** feature that makes comfortable to move for Jest

**Describe the solution you'd like**
Need to migrate to Jest after upgrade the project to angular 8

**Describe alternatives you've considered**
Yeah, we actually can move to another more suitable testing framework than Jest

**Comment by LayZeeDK** [comment]
Fixed by https://github.com/maktarsis/routeshub/pull/225.

**Comment by maktarsis** [comment]
Yeah, now we can close it.
