### ISSUE TITLE
Demo examples

### ISSUE THREAD

**Issue by maktarsis** [maktarsis/routeshub#215]
It'd be awesome to have more examples especially in online code editors like a stackblitz or codepen

**Comment by LayZeeDK** [comment]
StackBlitz has [GitHub integration](https://stackblitz.com/docs#import-from-github). To make it work, the example application should be on a separate branch (a clean branch with only an Angular CLI generated application) or a separate repository.

**Comment by maktarsis** [comment]
Yeah, I think it should work

Also, I wanna have different (separate) examples for different cases:
- simple (with the only root slice)
- medium (with root and a few feature slices)
- large (when feature slices have its own feature slices - increased tree)

I guess it will be more informative for those who want to see an emulation of "real world" case or for very quick solution to integrate and play with it

So, I think the first step should start from links you mentioned above, then separate that demo into increased/decreased examples. 

And in the end, we will have an excellent guide depending on the need.

**Comment by maktarsis** [comment]
calm down, stale bot
it's totally fine
